# Generated by Django 5.1 on 2024-08-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundId', models.CharField(max_length=255)),
                ('priceUSD', models.CharField(max_length=255)),
                ('timestamp', models.IntegerField(help_text='Unix timestamp')),
            ],
        ),
    ]
