# Generated by Django 5.1 on 2024-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ethereumprice_ethereumpricefeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumpricefeed',
            name='roundId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
